export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headline: "Unlimited Transactions with zero fees",
    description: "Get access to our exclusive app that allows you to make unlimited transactions without getting charged any fees.",
    buttonLabel: "Get Started",
    imgStart: false,
    img: "images/svg-1.svg",
    alt: 'Make it rain',
    dark: true,
    primary: true,
}

export const homeObjTwo = {
    id: "discover",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Unlimited Access",
    headline: "Login to your account at any time",
    description: "We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.",
    buttonLabel: "Learn More",
    imgStart: true,
    img: "images/svg-2.svg",
    alt: 'Piggy Bank',
    dark: false,
    primary: false,
}

export const homeObjThree = {
    id: "signup",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Join Our Team",
    headline: "Creating an account is extremely easy",
    description: "Get everything set up and ready within minutes. All you need to do is add your information and you're ready to go.",
    buttonLabel: "Start Now",
    imgStart: false,
    img: "images/svg-3.svg",
    alt: 'Papers',
    dark: false,
    primary: false,
}